DROP DATABASE IF EXISTS securitydb;
DROP USER IF EXISTS `securityadmin`@`%`;
DROP USER IF EXISTS `securityapp`@`%`;
CREATE DATABASE IF NOT EXISTS securitydb CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE USER IF NOT EXISTS `securityadmin`@`%` IDENTIFIED WITH mysql_native_password BY 'password';
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, REFERENCES, INDEX, ALTER, EXECUTE, CREATE VIEW, SHOW VIEW, CREATE ROUTINE, ALTER ROUTINE, EVENT, TRIGGER ON `securitydb`.* TO `securityadmin`@`%`;
CREATE USER IF NOT EXISTS `securityapp`@`%` IDENTIFIED WITH mysql_native_password BY 'password';
GRANT SELECT, INSERT, UPDATE, DELETE, SHOW VIEW ON `securitydb`.* TO `securityapp`@`%`;
FLUSH PRIVILEGES;