server:
  port: 8080
spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:securitydb
  jpa:
    defer-datasource-initialization: true
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  profiles:
    active: local, clean
logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace
  file:
    name: logs/local/security.log

